POST http://localhost:8080/events
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imsua2F1c2hhbDUwQGdtYWlsLmNvbSIsImV4cCI6MTc1NTc2NzA2NSwidXNlcklkIjoyfQ.Oz5eIShMKsKcogFVP6I5dgrWmTM12XvyNtYNTZqg1UA

{
  "name": "Sample Event",
  "location": "123 Main St, Anytown, USA",
  "date": "2025-08-18T15:30:00Z",
  "description": "This is a sample event description."
}