PUT http://localhost:8080/events/2
Content-Type: application/json
authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imsua2F1c2hhbDUwQGdtYWlsLmNvbSIsImV4cCI6MTc1NTc2NzA2NSwidXNlcklkIjoyfQ.Oz5eIShMKsKcogFVP6I5dgrWmTM12XvyNtYNTZqg1UA

{   
    "name": "Updated Event",
    "location": "Updated Location",
    "date": "2023-10-10T10:00:00Z",
    "description": "Updated Description",
    "user_id": 1
}